//atribuição normal
const a = 7;
let b = 3;

//atribuição aditiva.
b += a; // equivalente a : b = b + a.
console.log(b);

//atribuição subtrativa.
b -= 4; // equivalente a : b = b - 4.
console.log(b);

//atribuição multiplicativa
b *= 2; // equivalente a : b = b * 2.
console.log(b);

//atribuição divisiva
b /= 2; // equivalente a : b = b / 2.
console.log(b);

//atribuição modular
b %= 2; //  equivalente a : b = b % 2 , B for par o retorno é 0 senão é 1.
console.log(b);
